module.exports = Object.freeze({
    REGISTRATION_SUCCESS_MESSAGE: "Registered successfully.",
    REGISTRATION_FAILURE_MESSAGE: "Sorry for inconvenience! Facing something wrong while processing your request.",
    REGISTRATION_DEVICE_ID_FAIL: "Please Register With Same Device as You Verified Earliar.",
    LOGIN_SUCCESS: "Login Successful.",
    ACCOUNT_DISABLE:'Account Disable',
    LOGIN_FAILURE: "Sorry for inconvenience! Facing something wrong while processing your request.",
    EMAIL_NOTFOUND:'Email not Found',
    INVALID_PASSWORD:'Invalid Password',
    UPDATE_PASSWORD_SUCCESS: "Your password is successfully updated.",
    UPDATE_PASSWORD_FAILURE: "Sorry for inconvenience! Facing something wrong while processing your request.",
    FAILED_MSG: "Sorry for inconvenience! Facing something wrong while processing your request.",
    FAILED: "Server error.",
    INNGS_DUPLICATE: "Inngs duplicate data already exist.",
    CREATE_SUCCESS: "Created successfully.",
    SUCCESS: "success",
    ALREADY: "Already exist.",
    DULICATE: "Name/mobile number are already exist.",
    NOT_FOUND: 'Not found.',
    DATABASE_ERROR: "Not Getting Parent",
    FAILED_TO_SAVE: "Failed to save user data",
    PASSWORD_NOT_MATCH: "Password and ConfirmPassword not match",
    REGISTRATION_OTP: "OTP has been sent to your registered email",
    CREDENTIALS: "Enter valid credentials",
    OLD_PASSWORD: "Old password is incorrect",
    SEND_OTP: "OTP sent to your email address. OTP will expire in 10 min.",
    UPDATE_STATUS: "Update Status Successfully",
    WITHDRAW_AMOUNT: 'Withdrawa request approved and balance deducted successfully.',
    WITHDRAW_REQUEST: 'Withdraw request initiated successfully.',
    DEPOSIT_AMOUNT: 'Deposit amount request initiated successfully.',
    UPDATE_BANK: 'Bank details updated successfully.',
    ADD_BANK: 'Bank details added successfully.',
    DEVICE_ID: `dLNvpQxZRPykx96jvtjKss:APA91bE6zNwVmvz0TXTwr9Ijl-rkaurwi0WAYx42wq-G3iPSOl04DMjbVAXHDzevxeT2fWtKvmfO_73R9PQ095RPashK8BmNJ8_NTCOB49F2ZZDuw0uN_1TFgm30NgrrYEjXdkiJv4Ho`
});

