module.exports = Object.freeze({
    VERIFICATION_TOKEN_LENGTH: 40,
    OTP_LENGTH: 4,
    NOT_FOUND: 1404,
    SERVER_ERROR: 1500,
    SUCCESS: 1200,
    ACCESS_DENIED: 1403,
    NOT_VERIFIED: 1405,
    ERROR_TRUE: true,
    ERROR_FALSE: false,
    DATA_NULL: null,
    INVALID_TOKEN: 3,
    ERROR_CODE_ZERO: 0,
    ERROR_CODE_ONE: 1,
    ERROR_CODE_TWO: 2,
    MAINTENANCE_STATUS: 4,
    VALIDATION_MESSAGE: 5,
    USER_IS_DISABLED: 121,
    INSUFFICIENT_BALANCE: 1404,
    ALREADY_EXISTS: 1405,


});